language: python

# Command to install dependencies
install:
  - ./.travis-install-dependencies.sh

# Command to run tests
script:
  - regtests/runtests.sh

# Defines the branches on which the tests are run on
branches:
  only:
  - master
  - development

# Defines build stages.
jobs:
  include:
    - stage: test
      python: 3.5
      os: linux
    - stage: test
      python: 3.6
      os: linux
    - stage: test
      python: 3.7
      os: linux
      dist: xenial
      sudo: true
      after_success:
       - test $TRAVIS_BRANCH = "master" && coveralls && cd docs && ./buildtravisdocs.sh
    - stage: test
      python: 3.8
      os: linux
