# Defines when the pipeline is triggered
trigger:
- master

# Define the OS
pool:
  vmImage: 'ubuntu-latest'

# Stages
stages:
- stage: build
  jobs:
  - job:
        # Defines a parallel set of environments to run the pipeline on
    strategy:
      matrix:
        python35:
          python.version: '3.5'
        python36:
          python.version: '3.6'
        python37:
          python.version: '3.7'

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'
    - script: |
        ./.build.sh
      displayName: 'Build package'


- stage: test
  dependsOn: build
  jobs:
  - job:
    steps:
    - script: |
        regtests/runtests.sh
      displayName: 'Run regression tests'