# Defines when the pipeline is triggered
trigger:
- master

# Defines a parallel set of environments to run the pipeline on
strategy:
  matrix:
    python35:
      python.version: '3.5'
    python36:
      python.version: '3.6'
    python37:
      python.version: '3.7'

# Define the OS
pool:
  vmImage: 'ubuntu-latest'

# Jobs
jobs:

- job: build
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'
  - script: |
      cd $(Build.Repository.LocalPath)/CI && ./build.sh
    displayName: 'Build package'

- job: test
  dependsOn: build
  steps:
  - script: |
      cd $(Build.Repository.LocalPath)/CI && ./test.sh
    displayName: 'Run regression tests'