# Defines when the pipeline is triggered
trigger:
- master

# Define the OS
pool:
  vmImage: 'ubuntu-latest'

# Jobs
jobs:
- job: build
  strategy:
    matrix:
      python35:
        python.version: '3.5'
      python36:
        python.version: '3.6'
      python37:
        python.version: '3.7'
    maxParallel: 3
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'
  - script: |
      cd $(Build.Repository.LocalPath)/CI && ./build.sh
    displayName: 'Build package'

- job: test
  dependsOn: build
  steps:
  - script: |
      cd $(Build.Repository.LocalPath)/CI && ./test.sh
    displayName: 'Run regression tests'
